name: tigo
artifact: im-apps-broadcaster-tigo

apps:
    - 'django.contrib.contenttypes'
    - 'django.contrib.sessions'
    - 'django.contrib.staticfiles'
    - 'django.contrib.auth'

max_tps: 100
db_server_ip: localhost
db_server_port: 27017
db_name: broadcaster
watch_folder: /var/www/broadcaster/gt/tigo/watch/
working_folder: /var/www/broadcaster/gt/tigo/working/
done_folder: /var/www/broadcaster/gt/tigo/done/
reject_folder: /var/www/broadcaster/gt/tigo/rejects/
import_chunk_size: 100000
