name: tigo
artifact: im-apps-broadcaster-tigo

apps:
    - 'django.contrib.contenttypes'
    - 'django.contrib.sessions'
    - 'django.contrib.staticfiles'
    - 'django.contrib.auth'

max_tps: 100
db_server_ip: localhost
db_server_port: 27017
db_name: broadcaster
watch_folder: /Users/manuel/dev/git/broadcaster/watch/
working_folder: /Users/manuel/dev/git/broadcaster/working/
done_folder: /Users/manuel/dev/git/broadcaster/done/
reject_folder: /Users/manuel/dev/git/broadcaster/reject/
import_chunk_size: 1000000